import { spawn } from "node:child_process";
import { writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { resolve, relative } from "node:path";
import type { CleanupPlan, Report } from "../types.js";
import { formatMarkdown } from "../report/markdown.js";

export interface GitArgs {
  root: string;
  branch: string;
  filesChanged: string[];
  filesDeleted: string[];
}

export type GitResult =
  | { ok: true }
  | { ok: false; reason: string };

/**
 * Create (or switch to) `branch`, stage changes, and create a commit.
 * If `root` isn't a git repository, no-op with a structured reason.
 *
 * We intentionally do *not* push; users review locally and push themselves.
 */
export async function cleanupBranchAndCommit(args: GitArgs): Promise<GitResult> {
  if (!existsSync(resolve(args.root, ".git"))) {
    return { ok: false, reason: "not a git repository (no .git directory at root)" };
  }

  try {
    await git(["checkout", "-b", args.branch], args.root);
  } catch (err) {
    // Branch may already exist; try switching to it
    try {
      await git(["checkout", args.branch], args.root);
    } catch {
      return { ok: false, reason: `failed to create or switch to branch ${args.branch}: ${(err as Error).message}` };
    }
  }

  // Stage changes. We pass files explicitly to avoid sweeping in unrelated work.
  const staged: string[] = [];
  for (const f of args.filesChanged) staged.push(relative(args.root, f));
  for (const f of args.filesDeleted) staged.push(relative(args.root, f));
  if (!staged.length) {
    return { ok: false, reason: "no files to stage" };
  }

  try {
    await git(["add", "--", ...staged], args.root);
    await git(["commit", "-m", "chore: remove dead code (via deadcode-finder)"], args.root);
  } catch (err) {
    return { ok: false, reason: `git commit failed: ${(err as Error).message}` };
  }

  return { ok: true };
}

export interface PrDraftArgs {
  root: string;
  plan: CleanupPlan;
  report: Report;
  branch: string;
}

/**
 * Write a PR_DRAFT.md at the project root containing a suggested title, summary,
 * plan contents, and the full finding list. Users copy-paste into GitHub.
 */
export async function writePrDraft(args: PrDraftArgs): Promise<string> {
  const path = resolve(args.root, "PR_DRAFT.md");

  const lines: string[] = [];
  lines.push(`# chore: remove dead code`);
  lines.push("");
  lines.push(`Generated by \`deadcode-finder\` on \`${args.branch}\`.`);
  lines.push("");
  lines.push(`## Summary`);
  lines.push("");
  lines.push(`- Planned ${args.plan.items.length} cleanup item(s)`);
  if (args.plan.skipped.length) {
    lines.push(`- Skipped ${args.plan.skipped.length} finding(s) (see below)`);
  }
  lines.push("");
  lines.push(`## Applied cleanup`);
  lines.push("");
  for (const item of args.plan.items) {
    lines.push(`- ${item.description}`);
  }
  lines.push("");
  lines.push(`## Skipped findings`);
  lines.push("");
  if (!args.plan.skipped.length) {
    lines.push("_None_");
  } else {
    for (const s of args.plan.skipped) {
      lines.push(`- \`${s.findingId}\` — ${s.reason}`);
    }
  }
  lines.push("");
  lines.push(`## Full report`);
  lines.push("");
  lines.push(formatMarkdown(args.report));

  await writeFile(path, lines.join("\n"), "utf8");
  return path;
}

function git(args: string[], cwd: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn("git", args, { cwd, stdio: ["ignore", "pipe", "pipe"] });
    let stderr = "";
    child.stderr.on("data", (d) => (stderr += d.toString()));
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(stderr.trim() || `git ${args.join(" ")} exited with code ${code}`));
    });
    child.on("error", reject);
  });
}
